import Head from "next/head";
// import axios from "axios";
import { useEffect, useState } from "react";
// import renderHTML from "react-render-html";
import TopSlider from "../src/Components/Home/TopSlider";
import FindPartner from "../src/Components/Home/FindPartner";
import UpArrow from "../src/Components/Shared/upArrow";
import HowWorkThisSite from "../src/Components/Home/HowWorkThisSite";
import WhyUs from "../src/Components/Home/WhyUs";
import SuccessStories from "../src/Components/Home/SuccessStories";
import MembershipPlans from "../src/Components/Home/MembershipPlans";
import VIPAssistantService from "../src/Components/Home/VIPAssistantService";
import FilterSection from "../src/Components/Home/FilterSection";
import AppSection from "../src/Components/Home/AppSection";
import RegisterSection from "../src/Components/Home/RegisterSection";
import Faq from "../src/Components/Home/Faq";
import FooterSec from "../src/Components/Home/FooterSec";

export default function Home() {
  const [data, setData] = useState([]);

  // useEffect(() => {
  //   axios
  //     .get("http://localhost/wordpress/wp-json/wp/v2/media")
  //     .then((res) => setData(res.data));
  // }, []);

  // console.log(data);

  return (
    <>
      <Head>
        <title>Bibaho-Korbo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopSlider />
      <FindPartner />
      <HowWorkThisSite />
      <WhyUs />
      <SuccessStories />
      <MembershipPlans />
      <VIPAssistantService />
      <FilterSection />
      <AppSection />
      <RegisterSection />
      <Faq />
      <FooterSec />

      <UpArrow />
    </>
  );
}
